--- #YAML:1.0
name:               Rose-HTMLx-Form-DBIC
version:            0.05
abstract:           Integration of Rose::HTML::Form with DBIx::Class
author:
    - Zbigniew Lukasia
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBIx::Class::ResultSet::RecursiveUpdate:  0
    Moose:                0
    Rose::HTML::Object:   0.554
    Rose::Object:         0.85
    String::Random:       0
    Template:             0
    Test::Simple:         0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
